#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.
new_string="\\\tlocation /redirect_me {
        \n\t\t return 301 https://www.alxafrica.com;\n
    \t}\n"
sudo sed -i "$new_string" /etc/nginx/sites-available/default
sudo service nginx start
