#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page


new_string="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo sed -i "30i $new_string" /etc/nginx/sites-available/default
sudo service nginx start
