#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page


NEW_STRING="\\\tlocation /redirect_me {\n\t\t return 301 https://youtube.com;\n\t}\n"
ERROR_PAGE="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /var/www/html;\n\t\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $NEW_STRING" /etc/nginx/sites-available/default #add at line 30

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "s@$PATTERN@$ERROR_PAGE@" /etc/nginx/sites-available/default #uncomment and replace

sudo service nginx restart