#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page


new_string="\\\tlocation /redirect_me {\n\t\t return 301 https://youtube.com;\n\t}\n"
error_page="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
pattern="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $new_string" /etc/nginx/sites-available/default #add at line 30

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$pattern@$error_page@" /etc/nginx/sites-available/default #uncomment and replace

sudo service nginx restart