#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header - X-Served-B: <hostname>


HOST_NAME=$(hostname)
NEW_HEADER="\tadd_header X-Served-By $HOST_NAME"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "s/# server_tokens off;/server_tokens off;" /etc/nginx/nginx.conf
sudo sed -i "22a\ $NEW_HEADER" /etc/nginx/nginx.conf
sudo service nginx start
