#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "Hi" once after the 9th iteration

i=1
while ((i <= 11))
do
	if ((i == 10))
	then
		echo "Hi"
	else
	echo "Best School"
	fi
	((i++))
done
