#!/usr/bin/env bash
# Bash script that loops from 1 to 20 and:
	# displays 4 and then bad luck from China for the 4th loop iteration
	# displays 9 and then bad luck from Japan for the 9th loop iteration
	# displays 17 and then bad luck from Italy for the 17th loop iteration

i=1
while ((i <= 20))
do
	if ((i == 5))
	then
		echo "bad luck from China"
	elif ((i == 10))
	then
		echo "bad luck from Japan"
	elif ((i == 18))
	then
		echo "bad luck from Italy"
	else
	echo "$i"
	fi
	((i++))
done
